In [31]:
import pandas as pd
import tensorflow as tf

In [2]:
df = pd.read_csv('../data/house-prices.csv')
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

### Pré-processamento

In [6]:
colunas_usadas = df.columns[2:-2]
colunas_usadas

Index(['price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors',
       'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long'],
      dtype='object')

In [12]:
df = df.loc[:, df.columns.isin(colunas_usadas)]
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257
1,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319
2,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233
3,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393
4,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045

#### Escalonamento

In [16]:
from sklearn.preprocessing import MinMaxScaler # normalização, valores entre 0 e 1

In [22]:
scaler_x = MinMaxScaler()
df[df.columns[1:]] = scaler_x.fit_transform(df[df.columns[1:]])
df.head()

/home/dstrb/anaconda3/envs/tensor/lib/python3.6/site-packages/sklearn/preprocessing/data.py:323: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by MinMaxScaler.
  return self.partial_fit(X, y)

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,221900.0,0.090909,0.12500,0.067170,0.003108,0.0,0.0,0.0,0.5,0.500000,0.097588,0.000000,0.478261,0.000000,0.893939,0.571498,0.217608
1,538000.0,0.090909,0.28125,0.172075,0.004072,0.4,0.0,0.0,0.5,0.500000,0.206140,0.082988,0.443478,0.988089,0.626263,0.908959,0.166113
2,180000.0,0.060606,0.12500,0.036226,0.005743,0.0,0.0,0.0,0.5,0.416667,0.052632,0.000000,0.286957,0.000000,0.136364,0.936143,0.237542
3,604000.0,0.121212,0.37500,0.126038,0.002714,0.0,0.0,0.0,1.0,0.500000,0.083333,0.188797,0.565217,0.000000,0.681818,0.586939,0.104651
4,510000.0,0.090909,0.25000,0.104906,0.004579,0.0,0.0,0.0,0.5,0.583333,0.152412,0.000000,0.756522,0.000000,0.368687,0.741354,0.393688

In [24]:
scaler_y = MinMaxScaler()
df[['price']] = scaler_y.fit_transform(df[['price']])
df.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,0.019266,0.090909,0.12500,0.067170,0.003108,0.0,0.0,0.0,0.5,0.500000,0.097588,0.000000,0.478261,0.000000,0.893939,0.571498,0.217608
1,0.060721,0.090909,0.28125,0.172075,0.004072,0.4,0.0,0.0,0.5,0.500000,0.206140,0.082988,0.443478,0.988089,0.626263,0.908959,0.166113
2,0.013770,0.060606,0.12500,0.036226,0.005743,0.0,0.0,0.0,0.5,0.416667,0.052632,0.000000,0.286957,0.000000,0.136364,0.936143,0.237542
3,0.069377,0.121212,0.37500,0.126038,0.002714,0.0,0.0,0.0,1.0,0.500000,0.083333,0.188797,0.565217,0.000000,0.681818,0.586939,0.104651
4,0.057049,0.090909,0.25000,0.104906,0.004579,0.0,0.0,0.0,0.5,0.583333,0.152412,0.000000,0.756522,0.000000,0.368687,0.741354,0.393688

#### Classe / Previsores

In [26]:
X = df.drop('price', axis=1)
y = df.price

In [27]:
X.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,0.090909,0.12500,0.067170,0.003108,0.0,0.0,0.0,0.5,0.500000,0.097588,0.000000,0.478261,0.000000,0.893939,0.571498,0.217608
1,0.090909,0.28125,0.172075,0.004072,0.4,0.0,0.0,0.5,0.500000,0.206140,0.082988,0.443478,0.988089,0.626263,0.908959,0.166113
2,0.060606,0.12500,0.036226,0.005743,0.0,0.0,0.0,0.5,0.416667,0.052632,0.000000,0.286957,0.000000,0.136364,0.936143,0.237542
3,0.121212,0.37500,0.126038,0.002714,0.0,0.0,0.0,1.0,0.500000,0.083333,0.188797,0.565217,0.000000,0.681818,0.586939,0.104651
4,0.090909,0.25000,0.104906,0.004579,0.0,0.0,0.0,0.5,0.583333,0.152412,0.000000,0.756522,0.000000,0.368687,0.741354,0.393688

In [28]:
y.head()

0    0.019266
1    0.060721
2    0.013770
3    0.069377
4    0.057049
Name: price, dtype: float64

#### feature_column

In [33]:
colunas = [ tf.feature_column.numeric_column(key=c) for c in colunas_usadas[1:]]
colunas

[_NumericColumn(key='bedrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='bathrooms', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sqft_living', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sqft_lot', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='floors', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='waterfront', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='view', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='condition', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='grade', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sqft_above', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='sqft_basement', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='yr_built', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='yr_renovated', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='zipcode', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='lat', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None),
 _NumericColumn(key='long', shape=(1,), default_value=None, dtype=tf.float32, normalizer_fn=None)]

#### Split base

In [35]:
from sklearn.model_selection import train_test_split

In [36]:
X_treinamento, X_teste, y_treinamento, y_teste = train_test_split(X, y, test_size=.3)
X_treinamento.shape, X_teste.shape, y_treinamento.shape, y_teste.shape

((15129, 16), (6484, 16), (15129,), (6484,))

### Treinamento

In [38]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(
    x=X_treinamento,
    y=y_treinamento,
    batch_size=32,
    num_epochs=None,
    shuffle=True
)

In [39]:
funcao_teste = tf.estimator.inputs.pandas_input_fn(
    x=X_treinamento,
    y=y_treinamento,
    batch_size=32,
    num_epochs=10000,
    shuffle=False
)

In [40]:
regressor = tf.estimator.LinearRegressor(feature_columns=colunas)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: /tmp/tmpvsfoyh4p
INFO:tensorflow:Using config: {'_model_dir': '/tmp/tmpvsfoyh4p', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7fc820dd9518>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

In [41]:
regressor.train(input_fn=funcao_treinamento, steps=10000)

WARNING:tensorflow:From /home/dstrb/.local/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/queues/feeding_queue_runner.py:62: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
WARNING:tensorflow:From /home/dstrb/.local/lib/python3.6/site-packages/tensorflow/python/estimator/inputs/queues/feeding_functions.py:500: add_queue_runner (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
WARNING:tensorflow:From /home/dstrb/.local/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py:804: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
INFO:tensorflow:Saving checkpoints for 0 into /tmp/tmpvsfoyh4p/model.ckpt.
INFO:tensorflow:loss = 0.11607784, step = 1
INFO:tensorflow:global_step/sec: 512.49
INFO:tensorflow:loss = 0.015035743, step = 101 (0.196 sec)
INFO:tensorflow:global_step/sec: 611.523
INFO:tensorflow:loss = 0.0042526303, step = 201 (0.164 sec)
INFO:tensorflow:global_step/sec: 618.947
INFO:tensorflow:loss = 0.013768039, step = 301 (0.161 sec)
INFO:tensorflow:global_step/sec: 612.006
INFO:tensorflow:loss = 0.014803703, step = 401 (0.164 sec)
INFO:tensorflow:global_step/sec: 602.71
INFO:tensorflow:loss = 0.010190379, step = 501 (0.165 sec)
INFO:tensorflow:global_step/sec: 611.696
INFO:tensorflow:loss = 0.015661484, step = 601 (0.165 sec)
INFO:tensorflow:global_step/sec: 611.517
INFO:tensorflow:loss = 0.009891301, step = 701 (0.162 sec)
INFO:tensorflow:global_step/sec: 585.803
INFO:tensorflow:loss = 0.018404067, step = 801 (0.172 sec)
INFO:tensorflow:global_step/sec: 572.345
INFO:tensorflow:loss = 0.005895895, step = 901 (0.175 sec)
INFO:tensorflow:global_step/sec: 572.405
INFO:tensorflow:loss = 0.005224905, step = 1001 (0.174 sec)
INFO:tensorflow:global_step/sec: 497.446
INFO:tensorflow:loss = 0.038303252, step = 1101 (0.204 sec)
INFO:tensorflow:global_step/sec: 525.306
INFO:tensorflow:loss = 0.022808269, step = 1201 (0.189 sec)
INFO:tensorflow:global_step/sec: 584.997
INFO:tensorflow:loss = 0.008520404, step = 1301 (0.171 sec)
INFO:tensorflow:global_step/sec: 578.565
INFO:tensorflow:loss = 0.026600484, step = 1401 (0.173 sec)
INFO:tensorflow:global_step/sec: 575.631
INFO:tensorflow:loss = 0.011499872, step = 1501 (0.173 sec)
INFO:tensorflow:global_step/sec: 584.001
INFO:tensorflow:loss = 0.0049629686, step = 1601 (0.172 sec)
INFO:tensorflow:global_step/sec: 590.03
INFO:tensorflow:loss = 0.02401533, step = 1701 (0.173 sec)
INFO:tensorflow:global_step/sec: 563.657
INFO:tensorflow:loss = 0.008456003, step = 1801 (0.174 sec)
INFO:tensorflow:global_step/sec: 553.918
INFO:tensorflow:loss = 0.04057704, step = 1901 (0.180 sec)
INFO:tensorflow:global_step/sec: 561.456
INFO:tensorflow:loss = 0.08823848, step = 2001 (0.180 sec)
INFO:tensorflow:global_step/sec: 548.063
INFO:tensorflow:loss = 0.025636889, step = 2101 (0.181 sec)
INFO:tensorflow:global_step/sec: 575.348
INFO:tensorflow:loss = 0.024669608, step = 2201 (0.174 sec)
INFO:tensorflow:global_step/sec: 578.248
INFO:tensorflow:loss = 0.034163613, step = 2301 (0.173 sec)
INFO:tensorflow:global_step/sec: 584.494
INFO:tensorflow:loss = 0.012101217, step = 2401 (0.170 sec)
INFO:tensorflow:global_step/sec: 585.44
INFO:tensorflow:loss = 0.024671486, step = 2501 (0.172 sec)
INFO:tensorflow:global_step/sec: 574.389
INFO:tensorflow:loss = 0.016632285, step = 2601 (0.173 sec)
INFO:tensorflow:global_step/sec: 590.726
INFO:tensorflow:loss = 0.01013018, step = 2701 (0.169 sec)
INFO:tensorflow:global_step/sec: 588.037
INFO:tensorflow:loss = 0.027651876, step = 2801 (0.171 sec)
INFO:tensorflow:global_step/sec: 576.512
INFO:tensorflow:loss = 0.0088306125, step = 2901 (0.173 sec)
INFO:tensorflow:global_step/sec: 582.283
INFO:tensorflow:loss = 0.034615137, step = 3001 (0.171 sec)
INFO:tensorflow:global_step/sec: 578.557
INFO:tensorflow:loss = 0.021708608, step = 3101 (0.172 sec)
INFO:tensorflow:global_step/sec: 575.714
INFO:tensorflow:loss = 0.010535115, step = 3201 (0.173 sec)
INFO:tensorflow:global_step/sec: 581.729
INFO:tensorflow:loss = 0.020766132, step = 3301 (0.171 sec)
INFO:tensorflow:global_step/sec: 576.03
INFO:tensorflow:loss = 0.009637893, step = 3401 (0.175 sec)
INFO:tensorflow:global_step/sec: 591.887
INFO:tensorflow:loss = 0.008686882, step = 3501 (0.168 sec)
INFO:tensorflow:global_step/sec: 583.573
INFO:tensorflow:loss = 0.010630101, step = 3601 (0.171 sec)
INFO:tensorflow:global_step/sec: 577.957
INFO:tensorflow:loss = 0.01471127, step = 3701 (0.173 sec)
INFO:tensorflow:global_step/sec: 587.225
INFO:tensorflow:loss = 0.02028257, step = 3801 (0.171 sec)
INFO:tensorflow:global_step/sec: 586.538
INFO:tensorflow:loss = 0.012057145, step = 3901 (0.171 sec)
INFO:tensorflow:global_step/sec: 577.289
INFO:tensorflow:loss = 0.031623967, step = 4001 (0.172 sec)
INFO:tensorflow:global_step/sec: 572.364
INFO:tensorflow:loss = 0.008835584, step = 4101 (0.175 sec)
INFO:tensorflow:global_step/sec: 592.579
INFO:tensorflow:loss = 0.02062689, step = 4201 (0.168 sec)
INFO:tensorflow:global_step/sec: 585.923
INFO:tensorflow:loss = 0.018275812, step = 4301 (0.171 sec)
INFO:tensorflow:global_step/sec: 574.036
INFO:tensorflow:loss = 0.011489122, step = 4401 (0.175 sec)
INFO:tensorflow:global_step/sec: 585.775
INFO:tensorflow:loss = 0.0410494, step = 4501 (0.171 sec)
INFO:tensorflow:global_step/sec: 571.219
INFO:tensorflow:loss = 0.011162043, step = 4601 (0.175 sec)
INFO:tensorflow:global_step/sec: 592.859
INFO:tensorflow:loss = 0.0058689173, step = 4701 (0.167 sec)
INFO:tensorflow:global_step/sec: 580.176
INFO:tensorflow:loss = 0.0136119, step = 4801 (0.172 sec)
INFO:tensorflow:global_step/sec: 561.339
INFO:tensorflow:loss = 0.027525004, step = 4901 (0.180 sec)
INFO:tensorflow:global_step/sec: 587.364
INFO:tensorflow:loss = 0.017873112, step = 5001 (0.169 sec)
INFO:tensorflow:global_step/sec: 576.541
INFO:tensorflow:loss = 0.018176185, step = 5101 (0.173 sec)
INFO:tensorflow:global_step/sec: 531.25
INFO:tensorflow:loss = 0.025912613, step = 5201 (0.189 sec)
INFO:tensorflow:global_step/sec: 568.305
INFO:tensorflow:loss = 0.014812992, step = 5301 (0.176 sec)
INFO:tensorflow:global_step/sec: 587.388
INFO:tensorflow:loss = 0.01478539, step = 5401 (0.169 sec)
INFO:tensorflow:global_step/sec: 572.135
INFO:tensorflow:loss = 0.018663857, step = 5501 (0.176 sec)
INFO:tensorflow:global_step/sec: 580.941
INFO:tensorflow:loss = 0.011734176, step = 5601 (0.171 sec)
INFO:tensorflow:global_step/sec: 578.737
INFO:tensorflow:loss = 0.04400018, step = 5701 (0.174 sec)
INFO:tensorflow:global_step/sec: 587.203
INFO:tensorflow:loss = 0.021510622, step = 5801 (0.169 sec)
INFO:tensorflow:global_step/sec: 578.305
INFO:tensorflow:loss = 0.016623775, step = 5901 (0.174 sec)
INFO:tensorflow:global_step/sec: 588.527
INFO:tensorflow:loss = 0.02364369, step = 6001 (0.169 sec)
INFO:tensorflow:global_step/sec: 575.617
INFO:tensorflow:loss = 0.006487144, step = 6101 (0.173 sec)
INFO:tensorflow:global_step/sec: 597.546
INFO:tensorflow:loss = 0.013491448, step = 6201 (0.169 sec)
INFO:tensorflow:global_step/sec: 570.76
INFO:tensorflow:loss = 0.014006123, step = 6301 (0.173 sec)
INFO:tensorflow:global_step/sec: 595.027
INFO:tensorflow:loss = 0.010290678, step = 6401 (0.169 sec)
INFO:tensorflow:global_step/sec: 585.897
INFO:tensorflow:loss = 0.013318782, step = 6501 (0.171 sec)
INFO:tensorflow:global_step/sec: 582.992
INFO:tensorflow:loss = 0.015143144, step = 6601 (0.171 sec)
INFO:tensorflow:global_step/sec: 597.77
INFO:tensorflow:loss = 0.0119874505, step = 6701 (0.166 sec)
INFO:tensorflow:global_step/sec: 588.408
INFO:tensorflow:loss = 0.016674027, step = 6801 (0.171 sec)

INFO:tensorflow:global_step/sec: 594.372
INFO:tensorflow:loss = 0.014079801, step = 6901 (0.168 sec)
INFO:tensorflow:global_step/sec: 581.802
INFO:tensorflow:loss = 0.013472542, step = 7001 (0.172 sec)
INFO:tensorflow:global_step/sec: 593.688
INFO:tensorflow:loss = 0.033094972, step = 7101 (0.168 sec)
INFO:tensorflow:global_step/sec: 585.048
INFO:tensorflow:loss = 0.017334927, step = 7201 (0.171 sec)
INFO:tensorflow:global_step/sec: 595.4
INFO:tensorflow:loss = 0.02041497, step = 7301 (0.168 sec)
INFO:tensorflow:global_step/sec: 583.199
INFO:tensorflow:loss = 0.018054774, step = 7401 (0.171 sec)
INFO:tensorflow:global_step/sec: 582.254
INFO:tensorflow:loss = 0.061350673, step = 7501 (0.173 sec)
INFO:tensorflow:global_step/sec: 551.253
INFO:tensorflow:loss = 0.01211327, step = 7601 (0.182 sec)
INFO:tensorflow:global_step/sec: 580.402
INFO:tensorflow:loss = 0.01727096, step = 7701 (0.172 sec)
INFO:tensorflow:global_step/sec: 556.851
INFO:tensorflow:loss = 0.013428307, step = 7801 (0.179 sec)
INFO:tensorflow:global_step/sec: 587.563
INFO:tensorflow:loss = 0.022766648, step = 7901 (0.170 sec)
INFO:tensorflow:global_step/sec: 588.718
INFO:tensorflow:loss = 0.013451337, step = 8001 (0.171 sec)
INFO:tensorflow:global_step/sec: 585.371
INFO:tensorflow:loss = 0.02079947, step = 8101 (0.170 sec)
INFO:tensorflow:global_step/sec: 553.893
INFO:tensorflow:loss = 0.030010417, step = 8201 (0.182 sec)
INFO:tensorflow:global_step/sec: 560.11
INFO:tensorflow:loss = 0.021207305, step = 8301 (0.177 sec)
INFO:tensorflow:global_step/sec: 579.235
INFO:tensorflow:loss = 0.008517116, step = 8401 (0.174 sec)
INFO:tensorflow:global_step/sec: 588.026
INFO:tensorflow:loss = 0.08446136, step = 8501 (0.169 sec)
INFO:tensorflow:global_step/sec: 580.643
INFO:tensorflow:loss = 0.013746417, step = 8601 (0.172 sec)
INFO:tensorflow:global_step/sec: 582.847
INFO:tensorflow:loss = 0.007379939, step = 8701 (0.173 sec)
INFO:tensorflow:global_step/sec: 581.525
INFO:tensorflow:loss = 0.075895645, step = 8801 (0.172 sec)
INFO:tensorflow:global_step/sec: 570.578
INFO:tensorflow:loss = 0.008095814, step = 8901 (0.175 sec)
INFO:tensorflow:global_step/sec: 584.282
INFO:tensorflow:loss = 0.029140696, step = 9001 (0.170 sec)
INFO:tensorflow:global_step/sec: 589.465
INFO:tensorflow:loss = 0.04291047, step = 9101 (0.170 sec)
INFO:tensorflow:global_step/sec: 556.504
INFO:tensorflow:loss = 0.014146661, step = 9201 (0.180 sec)
INFO:tensorflow:global_step/sec: 528.558
INFO:tensorflow:loss = 0.02184828, step = 9301 (0.188 sec)
INFO:tensorflow:global_step/sec: 573.819
INFO:tensorflow:loss = 0.009515376, step = 9401 (0.175 sec)
INFO:tensorflow:global_step/sec: 547.161
INFO:tensorflow:loss = 0.008341107, step = 9501 (0.184 sec)
INFO:tensorflow:global_step/sec: 588.905
INFO:tensorflow:loss = 0.05123544, step = 9601 (0.168 sec)
INFO:tensorflow:global_step/sec: 620.909
INFO:tensorflow:loss = 0.015952643, step = 9701 (0.161 sec)
INFO:tensorflow:global_step/sec: 619.438
INFO:tensorflow:loss = 0.016925354, step = 9801 (0.161 sec)
INFO:tensorflow:global_step/sec: 602.887
INFO:tensorflow:loss = 0.018195396, step = 9901 (0.166 sec)
INFO:tensorflow:Saving checkpoints for 10000 into /tmp/tmpvsfoyh4p/model.ckpt.
INFO:tensorflow:Loss for final step: 0.010605151.

### Métricas

In [42]:
metricas_treinamento = regressor.evaluate(input_fn=funcao_treinamento, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-02-13-01:48:16
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpvsfoyh4p/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-02-13-01:48:32
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00069948734, global_step = 10000, label/mean = 0.060882542, loss = 0.022383595, prediction/mean = 0.05774878
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 10000: /tmp/tmpvsfoyh4p/model.ckpt-10000

In [43]:
metricas_teste = regressor.evaluate(input_fn=funcao_teste, steps=10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2019-02-13-01:48:47
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpvsfoyh4p/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Finished evaluation at 2019-02-13-01:49:03
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00070180313, global_step = 10000, label/mean = 0.06087625, loss = 0.0224577, prediction/mean = 0.057741284
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 10000: /tmp/tmpvsfoyh4p/model.ckpt-10000

In [44]:
metricas_treinamento

{'average_loss': 0.00069948734,
 'label/mean': 0.060882542,
 'loss': 0.022383595,
 'prediction/mean': 0.05774878,
 'global_step': 10000}

In [45]:
metricas_teste

{'average_loss': 0.00070180313,
 'label/mean': 0.06087625,
 'loss': 0.0224577,
 'prediction/mean': 0.057741284,
 'global_step': 10000}

### Predict

In [47]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(
    x=X_teste, 
    shuffle=False
)

In [51]:
previsoes = [ p['predictions'] for p in regressor.predict(input_fn=funcao_previsao)]

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/tmpvsfoyh4p/model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

In [54]:
previsoes[:5]

[array([0.14760403], dtype=float32),
 array([0.13384227], dtype=float32),
 array([0.15262295], dtype=float32),
 array([-0.00394379], dtype=float32),
 array([0.03570247], dtype=float32)]

### Mean Abs Error

In [59]:
import numpy as np
from sklearn.metrics import mean_absolute_error

In [56]:
valores_previsoes = np.asarray(previsoes).reshape(-1,1)

In [57]:
valores_previsoes = scaler_y.inverse_transform(valores_previsoes)
valores_previsoes[:5]

array([[1200480.8  ],
       [1095547.4  ],
       [1238750.   ],
       [  44928.633],
       [ 347231.38 ]], dtype=float32)

In [58]:
y_teste2 = scaler_y.inverse_transform(y_teste.values.reshape(-1,1))
y_teste2[:5]

array([[1200000.],
       [ 995000.],
       [1160000.],
       [ 175000.],
       [ 521500.]])

In [60]:
mean_absolute_error(y_teste2, valores_previsoes)

125861.19651308712